title: Site

sections:
  pages:
    type: pages

  brews:
    type: pages
    parent: site.find('brews')
    template: brew
    sortBy: brewed desc 
    status: all

  settings:
    type: fields
    fields:
      colorextractor:
        type: janitor
        label: Extract missing colors
        progress: 'Processing…'
        command: janitor:job --key sylvainjule.colorextractor.jobs.forceExtractColors

    
